export interface AppLanguage {
  code: string
  name: string // English name (used to instruct the AI)
  native: string // endonym (shown in the picker)
}

// Broad list of world languages (kept in sync conceptually with the iOS app).
export const LANGUAGES: AppLanguage[] = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'zh', name: 'Chinese (Simplified)', native: '简体中文' },
  { code: 'zh-Hant', name: 'Chinese (Traditional)', native: '繁體中文' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська' },
  { code: 'ro', name: 'Romanian', native: 'Română' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'th', name: 'Thai', native: 'ไทย' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά' },
  { code: 'cs', name: 'Czech', native: 'Čeština' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar' },
  { code: 'he', name: 'Hebrew', native: 'עברית' },
  { code: 'da', name: 'Danish', native: 'Dansk' },
  { code: 'fi', name: 'Finnish', native: 'Suomi' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina' },
  { code: 'bg', name: 'Bulgarian', native: 'Български' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski' },
  { code: 'sr', name: 'Serbian', native: 'Српски' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'fil', name: 'Filipino', native: 'Filipino' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans' },
  { code: 'sq', name: 'Albanian', native: 'Shqip' },
  { code: 'am', name: 'Amharic', native: 'አማርኛ' },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն' },
  { code: 'az', name: 'Azerbaijani', native: 'Azərbaycan' },
  { code: 'eu', name: 'Basque', native: 'Euskara' },
  { code: 'be', name: 'Belarusian', native: 'Беларуская' },
  { code: 'bs', name: 'Bosnian', native: 'Bosanski' },
  { code: 'my', name: 'Burmese', native: 'မြန်မာ' },
  { code: 'ca', name: 'Catalan', native: 'Català' },
  { code: 'ceb', name: 'Cebuano', native: 'Cebuano' },
  { code: 'co', name: 'Corsican', native: 'Corsu' },
  { code: 'eo', name: 'Esperanto', native: 'Esperanto' },
  { code: 'gl', name: 'Galician', native: 'Galego' },
  { code: 'ka', name: 'Georgian', native: 'ქართული' },
  { code: 'ht', name: 'Haitian Creole', native: 'Kreyòl Ayisyen' },
  { code: 'ha', name: 'Hausa', native: 'Hausa' },
  { code: 'is', name: 'Icelandic', native: 'Íslenska' },
  { code: 'ig', name: 'Igbo', native: 'Igbo' },
  { code: 'ga', name: 'Irish', native: 'Gaeilge' },
  { code: 'jw', name: 'Javanese', native: 'Basa Jawa' },
  { code: 'kk', name: 'Kazakh', native: 'Қазақ' },
  { code: 'km', name: 'Khmer', native: 'ខ្មែរ' },
  { code: 'ku', name: 'Kurdish', native: 'Kurdî' },
  { code: 'ky', name: 'Kyrgyz', native: 'Кыргызча' },
  { code: 'lo', name: 'Lao', native: 'ລາວ' },
  { code: 'la', name: 'Latin', native: 'Latina' },
  { code: 'lv', name: 'Latvian', native: 'Latviešu' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių' },
  { code: 'lb', name: 'Luxembourgish', native: 'Lëtzebuergesch' },
  { code: 'mk', name: 'Macedonian', native: 'Македонски' },
  { code: 'mg', name: 'Malagasy', native: 'Malagasy' },
  { code: 'mt', name: 'Maltese', native: 'Malti' },
  { code: 'mi', name: 'Maori', native: 'Māori' },
  { code: 'mn', name: 'Mongolian', native: 'Монгол' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली' },
  { code: 'ps', name: 'Pashto', native: 'پښتو' },
  { code: 'sm', name: 'Samoan', native: 'Gagana Samoa' },
  { code: 'gd', name: 'Scots Gaelic', native: 'Gàidhlig' },
  { code: 'st', name: 'Sesotho', native: 'Sesotho' },
  { code: 'sn', name: 'Shona', native: 'Shona' },
  { code: 'sd', name: 'Sindhi', native: 'سنڌي' },
  { code: 'si', name: 'Sinhala', native: 'සිංහල' },
  { code: 'so', name: 'Somali', native: 'Soomaali' },
  { code: 'su', name: 'Sundanese', native: 'Basa Sunda' },
  { code: 'tg', name: 'Tajik', native: 'Тоҷикӣ' },
  { code: 'tt', name: 'Tatar', native: 'Татар' },
  { code: 'tk', name: 'Turkmen', native: 'Türkmen' },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbek' },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa' },
  { code: 'yi', name: 'Yiddish', native: 'ייִדיש' },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá' },
  { code: 'zu', name: 'Zulu', native: 'isiZulu' },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina' },
  { code: 'et', name: 'Estonian', native: 'Eesti' },
  { code: 'lg', name: 'Luganda', native: 'Luganda' },
  { code: 'ny', name: 'Chichewa', native: 'Chichewa' },
  { code: 'rw', name: 'Kinyarwanda', native: 'Kinyarwanda' },
  { code: 'tn', name: 'Tswana', native: 'Setswana' },
  { code: 'wo', name: 'Wolof', native: 'Wolof' },
  { code: 'qu', name: 'Quechua', native: 'Runa Simi' },
  { code: 'gn', name: 'Guarani', native: 'Avañeʼẽ' },
  { code: 'om', name: "Oromo", native: 'Afaan Oromoo' },
  { code: 'ckb', name: "Kurdish (Sorani)", native: 'کوردیی ناوەندی' },
  { code: 'ber', name: "Tamazight", native: 'Tamaziɣt' },
  { code: 'dz', name: "Dzongkha", native: 'རྫོང་ཁ' },
  { code: 'bo', name: "Tibetan", native: 'བོད་སྐད' },
  { code: 'br', name: "Breton", native: 'Brezhoneg' },
  { code: 'oc', name: "Occitan", native: 'Occitan' },
  { code: 'ast', name: "Asturian", native: 'Asturianu' },
  { code: 'fo', name: "Faroese", native: 'Føroyskt' },
  { code: 'kl', name: "Kalaallisut", native: 'Kalaallisut' },
  { code: 'se', name: "Northern Sami", native: 'Davvisámegiella' },
  { code: 'gv', name: "Manx", native: 'Gaelg' },
  { code: 'kw', name: "Cornish", native: 'Kernewek' },
  { code: 'rm', name: "Romansh", native: 'Rumantsch' },
  { code: 'sc', name: "Sardinian", native: 'Sardu' },
  { code: 'scn', name: "Sicilian", native: 'Sicilianu' },
  { code: 'vec', name: "Venetian", native: 'Vèneto' },
  { code: 'lmo', name: "Lombard", native: 'Lombard' },
  { code: 'fur', name: "Friulian", native: 'Furlan' },
  { code: 'lad', name: "Ladino", native: 'Ladino' },
  { code: 'hsb', name: "Upper Sorbian", native: 'Hornjoserbsce' },
  { code: 'szl', name: "Silesian", native: 'Ślōnski' },
  { code: 'ab', name: "Abkhaz", native: 'Аҧсуа' },
  { code: 'os', name: "Ossetian", native: 'Ирон' },
  { code: 'ce', name: "Chechen", native: 'Нохчийн' },
  { code: 'cv', name: "Chuvash", native: 'Чӑваш' },
  { code: 'ba', name: "Bashkir", native: 'Башҡортса' },
  { code: 'sah', name: "Yakut", native: 'Саха' },
  { code: 'ban', name: "Balinese", native: 'Basa Bali' },
  { code: 'min', name: "Minangkabau", native: 'Baso Minang' },
  { code: 'mad', name: "Madurese", native: 'Madhurâ' },
  { code: 'war', name: "Waray", native: 'Winaray' },
  { code: 'pam', name: "Kapampangan", native: 'Kapampangan' },
  { code: 'hil', name: "Hiligaynon", native: 'Ilonggo' },
  { code: 'to', name: "Tongan", native: 'Lea faka-Tonga' },
  { code: 'fj', name: "Fijian", native: 'Vosa Vakaviti' },
  { code: 'ty', name: "Tahitian", native: 'Reo Tahiti' },
  { code: 'ch', name: "Chamorro", native: 'Chamoru' },
  { code: 'mh', name: "Marshallese", native: 'Kajin Majel' },
  { code: 'bi', name: "Bislama", native: 'Bislama' },
  { code: 'tpi', name: "Tok Pisin", native: 'Tok Pisin' },
  { code: 'ln', name: "Lingala", native: 'Lingála' },
  { code: 'kg', name: "Kongo", native: 'Kikongo' },
  { code: 'sg', name: "Sango", native: 'Sängö' },
  { code: 'ff', name: "Fula", native: 'Fulfulde' },
  { code: 'nd', name: "Ndebele", native: 'isiNdebele' },
  { code: 'ss', name: "Swati", native: 'siSwati' },
  { code: 've', name: "Venda", native: 'Tshivenḓa' },
  { code: 'bem', name: "Bemba", native: 'Ichibemba' },
  { code: 'luo', name: "Luo", native: 'Dholuo' },
  { code: 'ki', name: "Kikuyu", native: 'Gĩkũyũ' },
  { code: 'nv', name: "Navajo", native: 'Diné bizaad' },
  { code: 'chr', name: "Cherokee", native: 'ᏣᎳᎩ' },
  { code: 'iu', name: "Inuktitut", native: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'pap', name: "Papiamento", native: 'Papiamentu' },
]

export function deviceLanguageCode(): string {
  if (typeof navigator === 'undefined') return 'en'
  const code = (navigator.language || 'en').split('-')[0]
  return LANGUAGES.some((l) => l.code === code) ? code : 'en'
}

/** English name to instruct the AI with, or null for Auto / English. */
export function aiLanguageName(selection: string | undefined): string | null {
  const sel = selection || 'auto'
  if (sel === 'auto') return null
  if (sel === 'en') return null
  return LANGUAGES.find((l) => l.code === sel)?.name ?? null
}

export function languageDisplay(selection: string | undefined): string {
  const sel = selection || 'auto'
  if (sel === 'auto') {
    const d = LANGUAGES.find((l) => l.code === deviceLanguageCode())
    return `Auto · ${d?.native ?? 'English'}`
  }
  const l = LANGUAGES.find((x) => x.code === sel)
  return l ? `${l.native} — ${l.name}` : 'Auto'
}
