#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
SECRET_DIR="${HOME}/.openclaw-private"
ENV_FILE="${SECRET_DIR}/openclaw.env"
TELEGRAM_TOKEN_FILE="${SECRET_DIR}/telegram-bot.token"

prompt_secret() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="${!var_name:-}"
  if [[ -n "${current_value}" ]]; then
    return
  fi
  read -r -s -p "${prompt_text}: " current_value
  echo
  printf -v "${var_name}" '%s' "${current_value}"
}

append_export() {
  local key="$1"
  local value="$2"
  local escaped
  printf -v escaped '%q' "${value}"
  printf 'export %s=%s\n' "${key}" "${escaped}"
}

prompt_secret TELEGRAM_BOT_TOKEN "Telegram bot token"

: "${OPENCLAW_WORKSPACE:=${REPO_ROOT}}"
: "${OPENCLAW_CONFIG_PATH:=${OPENCLAW_WORKSPACE}/config/openclaw.json5}"
: "${OPENCLAW_TELEGRAM_TOKEN_FILE:=${TELEGRAM_TOKEN_FILE}}"

if [[ -z "${HF_TOKEN:-}" && -n "${HUGGINGFACE_HUB_TOKEN:-}" ]]; then
  HF_TOKEN="${HUGGINGFACE_HUB_TOKEN}"
fi

if [[ -z "${HUGGINGFACE_HUB_TOKEN:-}" && -n "${HF_TOKEN:-}" ]]; then
  HUGGINGFACE_HUB_TOKEN="${HF_TOKEN}"
fi

if [[ -z "${ELEVENLABS_API_KEY:-}" && -n "${XI_API_KEY:-}" ]]; then
  ELEVENLABS_API_KEY="${XI_API_KEY}"
fi

if [[ -z "${XI_API_KEY:-}" && -n "${ELEVENLABS_API_KEY:-}" ]]; then
  XI_API_KEY="${ELEVENLABS_API_KEY}"
fi

if [[ -z "${OPENROUTER_API_KEY:-}" && -z "${HF_TOKEN:-}" && -z "${HUGGINGFACE_HUB_TOKEN:-}" ]]; then
  prompt_secret OPENROUTER_API_KEY "OpenRouter API key"
fi

if [[ -f "${OPENCLAW_CONFIG_PATH}" ]] && grep -q '"provider": "elevenlabs"' "${OPENCLAW_CONFIG_PATH}" && [[ -z "${ELEVENLABS_API_KEY:-}" && -z "${XI_API_KEY:-}" ]]; then
  prompt_secret ELEVENLABS_API_KEY "ElevenLabs API key"
  XI_API_KEY="${ELEVENLABS_API_KEY}"
fi

if [[ -z "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  OPENCLAW_GATEWAY_TOKEN="$(openssl rand -hex 32)"
fi

mkdir -p "${SECRET_DIR}"
chmod 700 "${SECRET_DIR}"

printf '%s' "${TELEGRAM_BOT_TOKEN}" > "${TELEGRAM_TOKEN_FILE}"
chmod 600 "${TELEGRAM_TOKEN_FILE}"

: "${OPENCLAW_WORKSPACE:=${REPO_ROOT}}"
: "${OPENCLAW_CONFIG_PATH:=${OPENCLAW_WORKSPACE}/config/openclaw.json5}"
: "${OPENCLAW_TELEGRAM_TOKEN_FILE:=${TELEGRAM_TOKEN_FILE}}"

{
  echo "# Generated by scripts/wsl/write-secrets.sh"
  append_export OPENCLAW_WORKSPACE "${OPENCLAW_WORKSPACE}"
  append_export OPENCLAW_CONFIG_PATH "${OPENCLAW_CONFIG_PATH}"
  append_export OPENCLAW_TELEGRAM_TOKEN_FILE "${OPENCLAW_TELEGRAM_TOKEN_FILE}"
  append_export OPENCLAW_GATEWAY_TOKEN "${OPENCLAW_GATEWAY_TOKEN}"
  if [[ -n "${OPENROUTER_API_KEY:-}" ]]; then
    append_export OPENROUTER_API_KEY "${OPENROUTER_API_KEY}"
  fi
  if [[ -n "${HF_TOKEN:-}" ]]; then
    append_export HF_TOKEN "${HF_TOKEN}"
  fi
  if [[ -n "${HUGGINGFACE_HUB_TOKEN:-}" ]]; then
    append_export HUGGINGFACE_HUB_TOKEN "${HUGGINGFACE_HUB_TOKEN}"
  fi
  if [[ -n "${ELEVENLABS_API_KEY:-}" ]]; then
    append_export ELEVENLABS_API_KEY "${ELEVENLABS_API_KEY}"
  fi
  if [[ -n "${XI_API_KEY:-}" ]]; then
    append_export XI_API_KEY "${XI_API_KEY}"
  fi
} > "${ENV_FILE}"

chmod 600 "${ENV_FILE}"

echo "Wrote private env to ${ENV_FILE}"
echo "Wrote Telegram bot token to ${TELEGRAM_TOKEN_FILE}"
echo "Next: bash scripts/wsl/start-openclaw.sh config validate"
